### ISSUE TITLE
Polygon testing

### ISSUE THREAD

**Issue by phantomxe** [PistonDevelopers/piston-examples#450]
Hello, i'm trying to test polygon function and i got some problems with that. Firstly my base code is like,

```rust
...
let polys = &[
	[0.0, 0.0],
	[40.0, 0.0],
	[40.0, 20.0],
	[30.0, 20.0],
	[30.0, 40.0],
	[20.0, 40.0],
	[20.0, 30.0],
	[10.0, 30.0],
	[10.0, 40.0],
	[0.0, 40.0],
	[0.0, 0.0]
];

while let Some(e) = window.next() {
    window.draw_2d(&e, |c, g, _device| {
        clear([1.0; 4], g);
        polygon([1.0, 0.0, 1.0, 1.0],
				polys,
                c.transform.trans(40.0, 40.0, g);
        for item in polys {
                ellipse([0.0, 0.0, 1.0, 1.0],
                    ellipse::circle(item[0], item[1], 2.0),
                    c.transform.trans(40.0, 40.0, g);
        }
    });
}
...
```

But output is something fails,
![output2](https://user-images.githubusercontent.com/22988043/69476220-476b2780-0de8-11ea-891d-002a26cb37ca.png)

**Comment by writeoncereadmany** [comment]
This looks like it's displaying correctly to me, once you realise how polygons are drawn - it's a collection of triangles. In this case, a triangle fan. 

First, it'll draw a triangle using the first, second and third points, then the first, third, and fourth, then the first, fourth and fifth etc. 

That'll render any convex polygon correctly, and (accidentally) some concave polygons correctly - but you'll also get some shapes doing not-what-you-expected in the second leg.

In order to correctly draw concave polygons, you need to split them up into a combination of convex polygons.
